kind: ConfigMap
apiVersion: v1
metadata:
  name: busola-config
  namespace: kube-public
data:
  config: >
    {
      "config": {
        "storage": "localStorage",
        "features": {
          "EXTENSIBILITY_INJECTIONS": {
            "isEnabled": true
          }
        }
      }
    }
